//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AtlumerWebExamModel", "FK_tblQuestions_tblCategory", "tblCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebExam.tblCategory), "tblQuestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebExam.tblQuestion), true)]
[assembly: EdmRelationshipAttribute("AtlumerWebExamModel", "FK_tblChoices_tblQuestions", "tblQuestions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebExam.tblQuestion), "tblChoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebExam.tblChoice), true)]
[assembly: EdmRelationshipAttribute("AtlumerWebExamModel", "FK_tblScoreBoard_tblUserInfo", "tblUserInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebExam.tblUserInfo), "tblScoreBoard", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebExam.tblScoreBoard), true)]
[assembly: EdmRelationshipAttribute("AtlumerWebExamModel", "FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebExam.tblUserInfo), "tblSystemErrorLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebExam.tblSystemErrorLog), true)]
[assembly: EdmRelationshipAttribute("AtlumerWebExamModel", "FK_tblUserLogin_tblUserInfo", "tblUserInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebExam.tblUserInfo), "tblUserLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebExam.tblUserLogin), true)]

#endregion

namespace WebExam
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AtlumerWebExamEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AtlumerWebExamEntities object using the connection string found in the 'AtlumerWebExamEntities' section of the application configuration file.
        /// </summary>
        public AtlumerWebExamEntities() : base("name=AtlumerWebExamEntities", "AtlumerWebExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AtlumerWebExamEntities object.
        /// </summary>
        public AtlumerWebExamEntities(string connectionString) : base(connectionString, "AtlumerWebExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AtlumerWebExamEntities object.
        /// </summary>
        public AtlumerWebExamEntities(EntityConnection connection) : base(connection, "AtlumerWebExamEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCategory> tblCategories
        {
            get
            {
                if ((_tblCategories == null))
                {
                    _tblCategories = base.CreateObjectSet<tblCategory>("tblCategories");
                }
                return _tblCategories;
            }
        }
        private ObjectSet<tblCategory> _tblCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblChoice> tblChoices
        {
            get
            {
                if ((_tblChoices == null))
                {
                    _tblChoices = base.CreateObjectSet<tblChoice>("tblChoices");
                }
                return _tblChoices;
            }
        }
        private ObjectSet<tblChoice> _tblChoices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblQuestion> tblQuestions
        {
            get
            {
                if ((_tblQuestions == null))
                {
                    _tblQuestions = base.CreateObjectSet<tblQuestion>("tblQuestions");
                }
                return _tblQuestions;
            }
        }
        private ObjectSet<tblQuestion> _tblQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblScoreBoard> tblScoreBoards
        {
            get
            {
                if ((_tblScoreBoards == null))
                {
                    _tblScoreBoards = base.CreateObjectSet<tblScoreBoard>("tblScoreBoards");
                }
                return _tblScoreBoards;
            }
        }
        private ObjectSet<tblScoreBoard> _tblScoreBoards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSystemErrorLog> tblSystemErrorLogs
        {
            get
            {
                if ((_tblSystemErrorLogs == null))
                {
                    _tblSystemErrorLogs = base.CreateObjectSet<tblSystemErrorLog>("tblSystemErrorLogs");
                }
                return _tblSystemErrorLogs;
            }
        }
        private ObjectSet<tblSystemErrorLog> _tblSystemErrorLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUserInfo> tblUserInfoes
        {
            get
            {
                if ((_tblUserInfoes == null))
                {
                    _tblUserInfoes = base.CreateObjectSet<tblUserInfo>("tblUserInfoes");
                }
                return _tblUserInfoes;
            }
        }
        private ObjectSet<tblUserInfo> _tblUserInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUserLogin> tblUserLogins
        {
            get
            {
                if ((_tblUserLogins == null))
                {
                    _tblUserLogins = base.CreateObjectSet<tblUserLogin>("tblUserLogins");
                }
                return _tblUserLogins;
            }
        }
        private ObjectSet<tblUserLogin> _tblUserLogins;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCategories(tblCategory tblCategory)
        {
            base.AddObject("tblCategories", tblCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblChoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblChoices(tblChoice tblChoice)
        {
            base.AddObject("tblChoices", tblChoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblQuestions(tblQuestion tblQuestion)
        {
            base.AddObject("tblQuestions", tblQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblScoreBoards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblScoreBoards(tblScoreBoard tblScoreBoard)
        {
            base.AddObject("tblScoreBoards", tblScoreBoard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSystemErrorLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSystemErrorLogs(tblSystemErrorLog tblSystemErrorLog)
        {
            base.AddObject("tblSystemErrorLogs", tblSystemErrorLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUserInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUserInfoes(tblUserInfo tblUserInfo)
        {
            base.AddObject("tblUserInfoes", tblUserInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUserLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUserLogins(tblUserLogin tblUserLogin)
        {
            base.AddObject("tblUserLogins", tblUserLogin);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCategory object.
        /// </summary>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="availability">Initial value of the availability property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="createdDate">Initial value of the createdDate property.</param>
        public static tblCategory CreatetblCategory(global::System.String categoryID, global::System.String description, global::System.Boolean availability, global::System.String createdBy, global::System.DateTime createdDate)
        {
            tblCategory tblCategory = new tblCategory();
            tblCategory.categoryID = categoryID;
            tblCategory.description = description;
            tblCategory.availability = availability;
            tblCategory.createdBy = createdBy;
            tblCategory.createdDate = createdDate;
            return tblCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                if (_categoryID != value)
                {
                    OncategoryIDChanging(value);
                    ReportPropertyChanging("categoryID");
                    _categoryID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("categoryID");
                    OncategoryIDChanged();
                }
            }
        }
        private global::System.String _categoryID;
        partial void OncategoryIDChanging(global::System.String value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean availability
        {
            get
            {
                return _availability;
            }
            set
            {
                OnavailabilityChanging(value);
                ReportPropertyChanging("availability");
                _availability = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("availability");
                OnavailabilityChanged();
            }
        }
        private global::System.Boolean _availability;
        partial void OnavailabilityChanging(global::System.Boolean value);
        partial void OnavailabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private global::System.DateTime _createdDate;
        partial void OncreatedDateChanging(global::System.DateTime value);
        partial void OncreatedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblQuestions_tblCategory", "tblQuestions")]
        public EntityCollection<tblQuestion> tblQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblQuestion>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblQuestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblQuestion>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblQuestions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblChoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblChoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblChoice object.
        /// </summary>
        /// <param name="choicesID">Initial value of the choicesID property.</param>
        /// <param name="qID">Initial value of the qID property.</param>
        /// <param name="cText">Initial value of the cText property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="createdDate">Initial value of the createdDate property.</param>
        public static tblChoice CreatetblChoice(global::System.Int32 choicesID, global::System.String qID, global::System.String cText, global::System.String createdBy, global::System.DateTime createdDate)
        {
            tblChoice tblChoice = new tblChoice();
            tblChoice.choicesID = choicesID;
            tblChoice.qID = qID;
            tblChoice.cText = cText;
            tblChoice.createdBy = createdBy;
            tblChoice.createdDate = createdDate;
            return tblChoice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 choicesID
        {
            get
            {
                return _choicesID;
            }
            set
            {
                if (_choicesID != value)
                {
                    OnchoicesIDChanging(value);
                    ReportPropertyChanging("choicesID");
                    _choicesID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("choicesID");
                    OnchoicesIDChanged();
                }
            }
        }
        private global::System.Int32 _choicesID;
        partial void OnchoicesIDChanging(global::System.Int32 value);
        partial void OnchoicesIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String qID
        {
            get
            {
                return _qID;
            }
            set
            {
                OnqIDChanging(value);
                ReportPropertyChanging("qID");
                _qID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("qID");
                OnqIDChanged();
            }
        }
        private global::System.String _qID;
        partial void OnqIDChanging(global::System.String value);
        partial void OnqIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> correctAnswer
        {
            get
            {
                return _correctAnswer;
            }
            set
            {
                OncorrectAnswerChanging(value);
                ReportPropertyChanging("correctAnswer");
                _correctAnswer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("correctAnswer");
                OncorrectAnswerChanged();
            }
        }
        private Nullable<global::System.Boolean> _correctAnswer;
        partial void OncorrectAnswerChanging(Nullable<global::System.Boolean> value);
        partial void OncorrectAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cText
        {
            get
            {
                return _cText;
            }
            set
            {
                OncTextChanging(value);
                ReportPropertyChanging("cText");
                _cText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cText");
                OncTextChanged();
            }
        }
        private global::System.String _cText;
        partial void OncTextChanging(global::System.String value);
        partial void OncTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private global::System.DateTime _createdDate;
        partial void OncreatedDateChanging(global::System.DateTime value);
        partial void OncreatedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblChoices_tblQuestions", "tblQuestions")]
        public tblQuestion tblQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblQuestion>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblQuestions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblQuestion>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblQuestions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblQuestion> tblQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblQuestion>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblQuestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblQuestion>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblQuestions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblQuestion object.
        /// </summary>
        /// <param name="qID">Initial value of the qID property.</param>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="qContent">Initial value of the qContent property.</param>
        /// <param name="availability">Initial value of the availability property.</param>
        /// <param name="createdBy">Initial value of the createdBy property.</param>
        /// <param name="createdDate">Initial value of the createdDate property.</param>
        public static tblQuestion CreatetblQuestion(global::System.String qID, global::System.String categoryID, global::System.String qContent, global::System.Boolean availability, global::System.String createdBy, global::System.DateTime createdDate)
        {
            tblQuestion tblQuestion = new tblQuestion();
            tblQuestion.qID = qID;
            tblQuestion.categoryID = categoryID;
            tblQuestion.qContent = qContent;
            tblQuestion.availability = availability;
            tblQuestion.createdBy = createdBy;
            tblQuestion.createdDate = createdDate;
            return tblQuestion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String qID
        {
            get
            {
                return _qID;
            }
            set
            {
                if (_qID != value)
                {
                    OnqIDChanging(value);
                    ReportPropertyChanging("qID");
                    _qID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("qID");
                    OnqIDChanged();
                }
            }
        }
        private global::System.String _qID;
        partial void OnqIDChanging(global::System.String value);
        partial void OnqIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                OncategoryIDChanging(value);
                ReportPropertyChanging("categoryID");
                _categoryID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoryID");
                OncategoryIDChanged();
            }
        }
        private global::System.String _categoryID;
        partial void OncategoryIDChanging(global::System.String value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String qContent
        {
            get
            {
                return _qContent;
            }
            set
            {
                OnqContentChanging(value);
                ReportPropertyChanging("qContent");
                _qContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("qContent");
                OnqContentChanged();
            }
        }
        private global::System.String _qContent;
        partial void OnqContentChanging(global::System.String value);
        partial void OnqContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean availability
        {
            get
            {
                return _availability;
            }
            set
            {
                OnavailabilityChanging(value);
                ReportPropertyChanging("availability");
                _availability = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("availability");
                OnavailabilityChanged();
            }
        }
        private global::System.Boolean _availability;
        partial void OnavailabilityChanging(global::System.Boolean value);
        partial void OnavailabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private global::System.DateTime _createdDate;
        partial void OncreatedDateChanging(global::System.DateTime value);
        partial void OncreatedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblQuestions_tblCategory", "tblCategory")]
        public tblCategory tblCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCategory>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCategory>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCategory> tblCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCategory>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCategory>("AtlumerWebExamModel.FK_tblQuestions_tblCategory", "tblCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblChoices_tblQuestions", "tblChoices")]
        public EntityCollection<tblChoice> tblChoices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblChoice>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblChoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblChoice>("AtlumerWebExamModel.FK_tblChoices_tblQuestions", "tblChoices", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblScoreBoard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblScoreBoard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblScoreBoard object.
        /// </summary>
        /// <param name="scoreID">Initial value of the scoreID property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="set">Initial value of the set property.</param>
        /// <param name="totalItems">Initial value of the totalItems property.</param>
        /// <param name="dateTaken">Initial value of the DateTaken property.</param>
        public static tblScoreBoard CreatetblScoreBoard(global::System.Int32 scoreID, global::System.String userID, global::System.Int32 set, global::System.Int32 totalItems, global::System.DateTime dateTaken)
        {
            tblScoreBoard tblScoreBoard = new tblScoreBoard();
            tblScoreBoard.scoreID = scoreID;
            tblScoreBoard.userID = userID;
            tblScoreBoard.set = set;
            tblScoreBoard.totalItems = totalItems;
            tblScoreBoard.DateTaken = dateTaken;
            return tblScoreBoard;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 scoreID
        {
            get
            {
                return _scoreID;
            }
            set
            {
                if (_scoreID != value)
                {
                    OnscoreIDChanging(value);
                    ReportPropertyChanging("scoreID");
                    _scoreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("scoreID");
                    OnscoreIDChanged();
                }
            }
        }
        private global::System.Int32 _scoreID;
        partial void OnscoreIDChanging(global::System.Int32 value);
        partial void OnscoreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.String _userID;
        partial void OnuserIDChanging(global::System.String value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 set
        {
            get
            {
                return _set;
            }
            set
            {
                OnsetChanging(value);
                ReportPropertyChanging("set");
                _set = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("set");
                OnsetChanged();
            }
        }
        private global::System.Int32 _set;
        partial void OnsetChanging(global::System.Int32 value);
        partial void OnsetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalMistake
        {
            get
            {
                return _totalMistake;
            }
            set
            {
                OntotalMistakeChanging(value);
                ReportPropertyChanging("totalMistake");
                _totalMistake = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalMistake");
                OntotalMistakeChanged();
            }
        }
        private Nullable<global::System.Int32> _totalMistake;
        partial void OntotalMistakeChanging(Nullable<global::System.Int32> value);
        partial void OntotalMistakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalCorrect
        {
            get
            {
                return _totalCorrect;
            }
            set
            {
                OntotalCorrectChanging(value);
                ReportPropertyChanging("totalCorrect");
                _totalCorrect = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalCorrect");
                OntotalCorrectChanged();
            }
        }
        private Nullable<global::System.Int32> _totalCorrect;
        partial void OntotalCorrectChanging(Nullable<global::System.Int32> value);
        partial void OntotalCorrectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 totalItems
        {
            get
            {
                return _totalItems;
            }
            set
            {
                OntotalItemsChanging(value);
                ReportPropertyChanging("totalItems");
                _totalItems = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalItems");
                OntotalItemsChanged();
            }
        }
        private global::System.Int32 _totalItems;
        partial void OntotalItemsChanging(global::System.Int32 value);
        partial void OntotalItemsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTaken
        {
            get
            {
                return _DateTaken;
            }
            set
            {
                OnDateTakenChanging(value);
                ReportPropertyChanging("DateTaken");
                _DateTaken = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTaken");
                OnDateTakenChanged();
            }
        }
        private global::System.DateTime _DateTaken;
        partial void OnDateTakenChanging(global::System.DateTime value);
        partial void OnDateTakenChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblScoreBoard_tblUserInfo", "tblUserInfo")]
        public tblUserInfo tblUserInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblUserInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblUserInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUserInfo> tblUserInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblUserInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblUserInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblSystemErrorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSystemErrorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSystemErrorLog object.
        /// </summary>
        /// <param name="errID">Initial value of the errID property.</param>
        /// <param name="errDate">Initial value of the errDate property.</param>
        public static tblSystemErrorLog CreatetblSystemErrorLog(global::System.Int32 errID, global::System.DateTime errDate)
        {
            tblSystemErrorLog tblSystemErrorLog = new tblSystemErrorLog();
            tblSystemErrorLog.errID = errID;
            tblSystemErrorLog.errDate = errDate;
            return tblSystemErrorLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 errID
        {
            get
            {
                return _errID;
            }
            set
            {
                if (_errID != value)
                {
                    OnerrIDChanging(value);
                    ReportPropertyChanging("errID");
                    _errID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("errID");
                    OnerrIDChanged();
                }
            }
        }
        private global::System.Int32 _errID;
        partial void OnerrIDChanging(global::System.Int32 value);
        partial void OnerrIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.String _userID;
        partial void OnuserIDChanging(global::System.String value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String errWebPage
        {
            get
            {
                return _errWebPage;
            }
            set
            {
                OnerrWebPageChanging(value);
                ReportPropertyChanging("errWebPage");
                _errWebPage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("errWebPage");
                OnerrWebPageChanged();
            }
        }
        private global::System.String _errWebPage;
        partial void OnerrWebPageChanging(global::System.String value);
        partial void OnerrWebPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String errFunction
        {
            get
            {
                return _errFunction;
            }
            set
            {
                OnerrFunctionChanging(value);
                ReportPropertyChanging("errFunction");
                _errFunction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("errFunction");
                OnerrFunctionChanged();
            }
        }
        private global::System.String _errFunction;
        partial void OnerrFunctionChanging(global::System.String value);
        partial void OnerrFunctionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String errMessage
        {
            get
            {
                return _errMessage;
            }
            set
            {
                OnerrMessageChanging(value);
                ReportPropertyChanging("errMessage");
                _errMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("errMessage");
                OnerrMessageChanged();
            }
        }
        private global::System.String _errMessage;
        partial void OnerrMessageChanging(global::System.String value);
        partial void OnerrMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime errDate
        {
            get
            {
                return _errDate;
            }
            set
            {
                OnerrDateChanging(value);
                ReportPropertyChanging("errDate");
                _errDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("errDate");
                OnerrDateChanged();
            }
        }
        private global::System.DateTime _errDate;
        partial void OnerrDateChanging(global::System.DateTime value);
        partial void OnerrDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo")]
        public tblUserInfo tblUserInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUserInfo> tblUserInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblUserInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblUserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUserInfo object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="userType">Initial value of the userType property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="dateRegistered">Initial value of the dateRegistered property.</param>
        public static tblUserInfo CreatetblUserInfo(global::System.String userID, global::System.String userType, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.DateTime dateRegistered)
        {
            tblUserInfo tblUserInfo = new tblUserInfo();
            tblUserInfo.userID = userID;
            tblUserInfo.userType = userType;
            tblUserInfo.firstName = firstName;
            tblUserInfo.lastName = lastName;
            tblUserInfo.email = email;
            tblUserInfo.dateRegistered = dateRegistered;
            return tblUserInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.String _userID;
        partial void OnuserIDChanging(global::System.String value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userType
        {
            get
            {
                return _userType;
            }
            set
            {
                OnuserTypeChanging(value);
                ReportPropertyChanging("userType");
                _userType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userType");
                OnuserTypeChanged();
            }
        }
        private global::System.String _userType;
        partial void OnuserTypeChanging(global::System.String value);
        partial void OnuserTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String middleName
        {
            get
            {
                return _middleName;
            }
            set
            {
                OnmiddleNameChanging(value);
                ReportPropertyChanging("middleName");
                _middleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("middleName");
                OnmiddleNameChanged();
            }
        }
        private global::System.String _middleName;
        partial void OnmiddleNameChanging(global::System.String value);
        partial void OnmiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contact
        {
            get
            {
                return _contact;
            }
            set
            {
                OncontactChanging(value);
                ReportPropertyChanging("contact");
                _contact = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contact");
                OncontactChanged();
            }
        }
        private global::System.String _contact;
        partial void OncontactChanging(global::System.String value);
        partial void OncontactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateRegistered
        {
            get
            {
                return _dateRegistered;
            }
            set
            {
                OndateRegisteredChanging(value);
                ReportPropertyChanging("dateRegistered");
                _dateRegistered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateRegistered");
                OndateRegisteredChanged();
            }
        }
        private global::System.DateTime _dateRegistered;
        partial void OndateRegisteredChanging(global::System.DateTime value);
        partial void OndateRegisteredChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblScoreBoard_tblUserInfo", "tblScoreBoard")]
        public EntityCollection<tblScoreBoard> tblScoreBoards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblScoreBoard>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblScoreBoard");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblScoreBoard>("AtlumerWebExamModel.FK_tblScoreBoard_tblUserInfo", "tblScoreBoard", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblSystemErrorLog_tblUserInfo", "tblSystemErrorLog")]
        public EntityCollection<tblSystemErrorLog> tblSystemErrorLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSystemErrorLog>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblSystemErrorLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSystemErrorLog>("AtlumerWebExamModel.FK_tblSystemErrorLog_tblUserInfo", "tblSystemErrorLog", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblUserLogin_tblUserInfo", "tblUserLogin")]
        public EntityCollection<tblUserLogin> tblUserLogins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblUserLogin>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblUserLogin>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserLogin", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AtlumerWebExamModel", Name="tblUserLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUserLogin object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="userPwd">Initial value of the userPwd property.</param>
        /// <param name="userType">Initial value of the userType property.</param>
        /// <param name="isActive">Initial value of the isActive property.</param>
        /// <param name="pwdLastUpdate">Initial value of the pwdLastUpdate property.</param>
        /// <param name="lastLogin">Initial value of the lastLogin property.</param>
        public static tblUserLogin CreatetblUserLogin(global::System.String userID, global::System.String userPwd, global::System.String userType, global::System.Boolean isActive, global::System.DateTime pwdLastUpdate, global::System.DateTime lastLogin)
        {
            tblUserLogin tblUserLogin = new tblUserLogin();
            tblUserLogin.userID = userID;
            tblUserLogin.userPwd = userPwd;
            tblUserLogin.userType = userType;
            tblUserLogin.isActive = isActive;
            tblUserLogin.pwdLastUpdate = pwdLastUpdate;
            tblUserLogin.lastLogin = lastLogin;
            return tblUserLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.String _userID;
        partial void OnuserIDChanging(global::System.String value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userPwd
        {
            get
            {
                return _userPwd;
            }
            set
            {
                if (_userPwd != value)
                {
                    OnuserPwdChanging(value);
                    ReportPropertyChanging("userPwd");
                    _userPwd = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userPwd");
                    OnuserPwdChanged();
                }
            }
        }
        private global::System.String _userPwd;
        partial void OnuserPwdChanging(global::System.String value);
        partial void OnuserPwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userType
        {
            get
            {
                return _userType;
            }
            set
            {
                if (_userType != value)
                {
                    OnuserTypeChanging(value);
                    ReportPropertyChanging("userType");
                    _userType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("userType");
                    OnuserTypeChanged();
                }
            }
        }
        private global::System.String _userType;
        partial void OnuserTypeChanging(global::System.String value);
        partial void OnuserTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isActive
        {
            get
            {
                return _isActive;
            }
            set
            {
                if (_isActive != value)
                {
                    OnisActiveChanging(value);
                    ReportPropertyChanging("isActive");
                    _isActive = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("isActive");
                    OnisActiveChanged();
                }
            }
        }
        private global::System.Boolean _isActive;
        partial void OnisActiveChanging(global::System.Boolean value);
        partial void OnisActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime pwdLastUpdate
        {
            get
            {
                return _pwdLastUpdate;
            }
            set
            {
                if (_pwdLastUpdate != value)
                {
                    OnpwdLastUpdateChanging(value);
                    ReportPropertyChanging("pwdLastUpdate");
                    _pwdLastUpdate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pwdLastUpdate");
                    OnpwdLastUpdateChanged();
                }
            }
        }
        private global::System.DateTime _pwdLastUpdate;
        partial void OnpwdLastUpdateChanging(global::System.DateTime value);
        partial void OnpwdLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastLogin
        {
            get
            {
                return _lastLogin;
            }
            set
            {
                if (_lastLogin != value)
                {
                    OnlastLoginChanging(value);
                    ReportPropertyChanging("lastLogin");
                    _lastLogin = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("lastLogin");
                    OnlastLoginChanged();
                }
            }
        }
        private global::System.DateTime _lastLogin;
        partial void OnlastLoginChanging(global::System.DateTime value);
        partial void OnlastLoginChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AtlumerWebExamModel", "FK_tblUserLogin_tblUserInfo", "tblUserInfo")]
        public tblUserInfo tblUserInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUserInfo> tblUserInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUserInfo>("AtlumerWebExamModel.FK_tblUserLogin_tblUserInfo", "tblUserInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
